version: 2.1

orbs:
  python: circleci/python@1.3.4

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.7.9

    working_directory: ~/repo

    steps:
      - checkout
      - python/install-packages

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "FlightReservationAPI/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r FlightReservationAPI/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd FlightReservationAPI
            python manage.py test

      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1