# Generated by Django 3.2 on 2021-04-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightAPP', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='operatingAirlines',
            new_name='operatingAirline',
        ),
    ]
