# Generated by Django 3.2 on 2021-04-13 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightAPP', '0002_rename_operatingairlines_flight_operatingairline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='arrivalCity',
            new_name='arrival_city',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='dateOfDeparture',
            new_name='date_of_departure',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='departureCity',
            new_name='departure_city',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='estimatedTimeOfDeparture',
            new_name='estimated_time_of_departure',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flightNumber',
            new_name='flight_number',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='operatingAirline',
            new_name='operating_airline',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='passenger',
            old_name='middleName',
            new_name='middle_name',
        ),
    ]
